awsdocs/amazon-ecs-developer-guide

- doc_source/task_definition_parameters.md
Updated sentence to make sense by adding 'launch type' for two Fargate sentences
> Updated sentence to have correct wording, including 'launch type'

- doc_source/troubleshoot-task-iam-roles.md
Role is still named "EC2ContainerService", so that was not updated.
Updated service name from `EC2 Container Service` to `Elastic Container Service`
> Updating service name to Elastic Container Service

- doc_source/Welcome.md
According to [Task Definition Parameters/Task Size](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size):
For `cpu`:
> If using the Fargate launch type, this field is required and you must use one of the following values, which determines your range of supported values for the memory parameter: 
* 256
* 512
* etc.
and for `memory`:
> If using the Fargate launch type, this field is required and you must use one of the following values, which determines your range of supported values for the cpu parameter: 
* 512
* 1024
* etc.
The example uses the `FARGATE` launch type, so it cannot use 100 and 99 for memory and cpu, respectively.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Made Example Task Definition use valid values

- doc_source/ecs-cd-pipeline.md
Fallback mechanism to avoid getting error when CODEBUILD_RESOLVED_SOURCE_VERSION not present.
> Avoid error when source version not present

- doc_source/task-placement-constraints.md
*Issue #, if available:* N/A
*Description of changes:* Updated the Task Placement Constraints to reflect the fact that it is not possible to create a distinctInstance constraint with a Task Definition. When this is performed an error will be thrown by the API.
> clarified that distinctInstance is not supported on Task Definitions

- doc_source/task-metadata-endpoint-v3.md
This PR fixes the paths in the Task Metadata Endpoint v3 doc. It returns 404 if the urls include the trailing slashes.
> Fix wrong paths within the Task Metadata Endpoint v3 doc

- doc_source/specifying-sensitive-data.md
Fixed typo 'tchoose' to 'choose'
There is a typo in the doc with 'tchoose'. It should be 'choose'.
> Fixed typo

- doc_source/task_definition_parameters.md
Added clarification when there are multiple arguments, each argument should be a separated string in the array. Eg:
Instead of:
```
"command": [
["/usr/bin/java -Dserver.port=8081 -jar service.jar"]
]
```
The correct way should be: 
```
"command": [
"/usr/bin/java", "-Dserver.port=8081", "-jar", "service.jar"
]
```
> Update TaskDefinition - CMD description

- doc_source/ecs-agent-config.md
Log driver supports: https://github.com/aws/amazon-ecs-agent/blob/c0defea9598061451cf5ffd452d2ffe3d91dbc5e/agent/dockerclient/logging_drivers.go
Configuration doc and API doc should support this.
> configuration to include other log drivers

- doc_source/launch_container_instance.md
One example shows `cat &lt;&lt;'EOF' >> /etc/ecs/ecs.config` which should be `cat <<'EOF' >> /etc/ecs/ecs.config`. Fix it to avoid reader miss configuration.
#60 
One example shows `cat &lt;&lt;'EOF' >> /etc/ecs/ecs.config` which should be `cat <<'EOF' >> /etc/ecs/ecs.config` in the page `Launching an Amazon ECS Container Instance`.
> Fix `&lt;&lt;` in User data example of the page `Launching an Amazon ECS Container Instance`.

- doc_source/windows_task_IAM_roles.md
The PowerShell command Get-WMIObject module is deprecated since windows 2012 and updated a correct command Get-NetRoute suitable for even windows nanoserver docker image.
> Replacing deprecated command with correct command

- doc_source/docker-basics.md
The Task in the provided example is called hello-world. This is the name we need to use for the run-task API call, not the Container Name. That will return an error and confuse new users.
> Fix typos in Docker Basics documentation page

- doc_source/launch_container_instance.md
Fixed a minor typo by removing the unnecessary "Specify a" words.
> Fix a typo in the Launch Container Instance documentation

- doc_source/service_definition_parameters.md
The `enableECSManagedTags` property was located between the`tags` property and the sub-properties of `tags` when it's not a sub-property of `tags`
> Fix placement of the enableECSManagedTags parameter definition

- doc_source/ec2-run-command.md
This change is also consistent with other `yum` usage in this guide:
`yum install -y ecs-init` [1], `yum install -y awslogs` [2].
[1] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html
[2] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html
> `yum install` already uses the current region

- doc_source/ECS_Windows_getting_started.md
Microsoft IIS Docker image has changed the entrypoint to: `C:\ServiceMonitor.exe w3svc` to keep the container running. With the current task definition, the container will exit in a few seconds. Adding ServiceMonitor.exe after modifying the index.html file fixes the problem and keep container running. More information about ServiceMonitor can be found at: 
[https://github.com/microsoft/IIS.ServiceMonitor](https://github.com/microsoft/IIS.ServiceMonitor)
The idea of adding `C:\ServiceMonitor.exe w3svc` is based on [https://github.com/microsoft/iis-docker/blob/master/windowsservercore-1903/Dockerfile](https://github.com/microsoft/iis-docker/blob/master/windowsservercore-1903/Dockerfile)
Also fix the syntax error --Force should be -Force (single dash).
By submitting …
> Fixed broken IIS task definition due to entrypoint changes

- doc_source/ecs-using-tags.md
tags containing the AWS: or Aws: (upper/lower case) prefixes are not allowed as well
Fixes issue #72
Changes wording around tags restrictions
> Fixes issue #72

- doc_source/cmd-ecs-cli-configure.md
The current version of `ecs-cli` (1.14.1) produces the updated output.
> docs: correct config output

- doc_source/ecs-cli-tutorial-fargate.md
Running just `ecs-cli up` won't work for users who previously created a different cluster with ecs-cli. Adding the `--cluster` flag will make this tutorial work for everyone without needing to modify the example code.
> Added --cluster flag to ecs-cli up

- doc_source/ecs-cli-tutorial-fargate.md
*Issue #, if available:* 
- N/A
- Step 6 & Step 9 has the same `a` tag id
- This caused the right navigation bar to highlight step 6 when step 9 is viewed
> Change duplicate html tag id

- doc_source/scheduled_tasks.md
In CloudWatch IAM role - iam:PassRole permission are also required for task role.
adding requirement of iam:PassRole permission if task definition has task role specified.
> requirement of iam:PassRole for task role - scheduled_tasks.md

- doc_source/CWE_IAM_role.md
In CloudWatch IAM role - iam:PassRole permission are also required for task role.
Changes in addition to https://github.com/awsdocs/amazon-ecs-developer-guide/blob/master/doc_source/scheduled_tasks.md
adding requirement of iam:PassRole permission if task definition has task role specified.
> requirement of iam:PassRole for task role - CWE_IAM_role.md

- doc_source/task_IAM_role.md
Fixes issue #87
The paragraph: "Before you can use IAM roles for tasks, Amazon ECS needs permission to make calls to the AWS APIs on your behalf. These permissions are provided by the Amazon ECS Task Role." is unclear and removing it won't make a difference.
These permissions are either provided by the trust policy for "ecs-task.amazonaws.com" or something else.
> Remove unclear paragraph about IAM role requisites

- doc_source/ecs-cd-pipeline.md
The line I am editing is 
>> The `imagedefinitions.json` file is required for the CodeDeploy ECS job worker\.
To:
The `imagedefinitions.json` file is required for the ECS job worker\.
CodeDeploy ECS job worker is for Blue/Green deployment not the standard one. The CodeDeploy ECS job worker needs file "imageDetail.json" for Amazon ECS Blue/Green Deployment Actions and not "imagedefinitions.json". When you mention the word CodeDeploy in this tutorial, it causes confusion that this is a Blue/Green deployment which this is not.
> Remove reference to "CodeDeploy"

- doc_source/ecs-cd-pipeline.md
This tag is specific to the sample app that was used in this tutorial. It is unclear for those who follow the tutorial, that the tag needs to be changed as well. Using `latest` abstracts away this issue.
> fix: docker image tag

- doc_source/service_definition_parameters.md
Updated the healthCheckGracePeriodSeconds to be more explicit as to when the timing begins. 
Updated the working to "after a task enters the RUNNING state"
> updated healthCheckGracePeriodSeconds

- doc_source/ECS-AMI-SubscribeTopic.md
*Issue 103:*
Link to "Tutorial: Subscribing an Amazon SQS Queue to an Amazon SNS Topic" in the third paragraph did not point to the SQS tutorial.
Placed the link to the SQS tutorial.
> Placed a link to SQS tutorial

- doc_source/ecs-cd-pipeline.md
The current documentation provides incorrect instructions on Step2 -> Item 5 -> Items b-g. It instructs the user to use the image that will be built in CodeBuild as the build image itself, which most of the time will not work since this is will be the application image to be deployed in ECS. Instead of that, we should use one of the standard CodeBuild images, which provides the utilities necessary to build Docker images.
The changes in this pull request change the instructions to guide users to use the standard Amazon Linux 2 docker image as the build image, and adds additional buildspec code to support that.
> Fix incorrect and outdated CodeBuild instructions

- doc_source/ecs-agent-config.md
ECS_ENABLE_SPOT_INSTANCE_DRAINING was defined twice so I removed the less descriptive entry.
> Remove duplicate definition of ECS_ENABLE_SPOT_INSTANCE_DRAINING

- doc_source/fargate-capacity-providers.md
*Issue #, if available:* 
RunTask and Service for Fargate needs awsvpcConfiguration as a mandatory parameter for AWS CLI.
> added --network-configuration

- doc_source/create-blue-green.md
*Issue #, if available:* N/A
Fix typo in the sample file for the `aws deploy create-deployment-group` command.
The default named used in the previous command when creating the CodeDeploy application is `tutorial-bluegreen-app`.
This commit changes the incorrect `=` to `-`.
This allows customers to easily copy/paste these commands and json files.
---
> create-blue-green.md: Fix typo

- doc_source/create-blue-green.md
*Issue #, if available:* N/A
Update the default command for `aws deploy get-deployment-target` to work with the default values used previously.
The API error message explains what the format of the `--target-id` argument should be:
```
An error occurred (InvalidDeploymentTargetIdException) when calling the GetDeploymentTarget operation: Invalid id tutorial-bluegreen-cluster for ECS deployment, valid Id should be in format <cluster-name>:<service-name>
```
And in this example, the default value for `<cluster-name>` is `tutorial-bluegreen-cluster`, not `tutorial-bluegreen-app` (which is the name of the CodeDeploy application.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> create-blue-green.md: Fix get-deployment-target

- doc_source/api_failures_messages.md
RunTask fails with LOCATION error when there is a mismatch AZ of instance and awsvpcConfiguration.
> added description and fix for LOCATION error.

- doc_source/ECS_CLI_installation.md
*Issue #, if available:* n/a
Update the Windows ECS CLI installation command, which currently fails due to bad quoting.
**Before:**
```PowerShell
PS > New-Item ‘C:\Program Files\Amazon\ECSCLI’ -type directory
New-Item: A positional parameter cannot be found that accepts argument 'Files\Amazon\ECSCLI'.
```
**After:**
```PowerShell
PS > New-Item -Path 'C:\Program Files\Amazon\ECSCLI' -ItemType Directory
Directory: C:\Program Files\Amazon
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2020-03-21  4:36 PM                ECSCLI
```
> Update Windows ECS CLI installation commands

- doc_source/efs-volumes.md
There's a missing s in tranitEncryption param name. Moreover, the transitEncryptionPort was used instead of authorizationConfig :wink:
> Fix typos in the example efsVolumeConfiguration 

- doc_source/bootstrap_container_instance.md
The reference was pointing to item 7, but the target documentation was updated. To avoid confusing the customer, the new destination position should be used.
Updated the cross documentation reference.
> Fix cross documentation reference

- doc_source/task_definition_parameters.md
This is already supported by Fargate and ECS, no error will be returned.
*Description of changes:* I have removed the note that states that an error will be thrown if a task definition is created on both TCP and UDP ports, as this is no longer true
> Removed Note for Same port on UDP and TCP

- doc_source/task-metadata-endpoint-v2.md
- doc_source/task-metadata-endpoint-v3.md
- doc_source/task-metadata-endpoint-v4.md
No issue
Cluster definition was wrong as it only returns ARN if it is set on the ecs.config file, otherwise returns the cluster name.
> fixed cluster task metadata endpoint definition

- doc_source/asg-capacity-providers.md
The issue is related to the requirement for ASG to meet the minimum requirements for predictive scaling. When ASG has other scaling policies, this can cause ECS scaling plan to run into activeWithProblem
Added requirements on scaling policies
> Added Auto Scaling group consideration to enable managed scaling

- doc_source/task_definition_parameters.md
This is just a tiny formatting issue; all other log drivers have double quotes, so close the last one with it too.
> Add missing trailing quote to awsfirelens logDriver

- doc_source/ecs_cwe_events.md
Adds in a few missing commas from (currently invalid) JSON examples of Service deployment state change events. 
> Adding missing comma to json examples

- doc_source/service-quotas.md
According to my testing, I can create task definition over `32K`. I think the limit as mentioned on the doc should be corrected. When I tried to create a task definition over 64K, following error will appear:
```
Unable to create a new revision of Task Definition
Actual length: '66420'. Max allowed length is '65536' bytes.
```
CloudTrail event:
```
"eventTime": "2021-01-21T16:24:09Z",
"eventSource": "ecs.amazonaws.com",
"eventName": "RegisterTaskDefinition",
"awsRegion": "ap-northeast-1",
"userAgent": "console.amazonaws.com",
"errorCode": "ClientException",
"errorMessage": "Actual length: '66420'. Max allowed length is '65536' bytes.",
"requestParameters": null,
"responseElements": null,
```
**So help to update the task definition size …
> Propose the correct task definition size limit

- doc_source/AWS_Fargate.md
- doc_source/fargate-task-storage.md
*Issue #, if available* : The position of the note `The host and sourcePath parameters are not supported for Fargate tasks` is confusing. Since the note is under `Fargate tasks using platform version 1.3.0 or earlier`. But whatever the Fargate version is (even version 1.4.0), Fargate tasks are not able to specify host and sourcePath parameters in the task definition. 
*Description of changes:* Change the note `The host and sourcePath parameters are not supported for Fargate tasks` position
> Modify the position of host and sourcePath parameters note

- doc_source/getting-started-aws-copilot-cli.md
Since external users are not part of the repository, HTTPS should be used as protocol for Git operations instead of SSH.
> Use HTTP instead of SSH for Git clone

- doc_source/ecs-exec.md
The managed agents for ECS Exec (= SSM agents at this moment) require writable filesystems to create the required files and directories to work. Adding this note to the documentation would make troubleshooting easier for users.  
> Clarify ECS Exec cannot be used with read-only filesystem containers

- doc_source/ecs_services.md
Nothing more than a spell correct
> Correct Spelling of 'container'

- doc_source/security-iam-awsmanpol.md
Hi, there!
Some links on this page are broken because the path format is invalid (lack of the first `/`), then I updated them!
Please check the links actually expired on the page: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/security-iam-awsmanpol.html
> Update expired links in security-iam-awsmanpol.md

- doc_source/http_proxy_config.md
N/A
As described in the [Docker documentation](https://docs.docker.com/network/proxy/), `HTTP_PROXY` requires the url scheme part in addition to host and port.
> Fix missing url scheme

- doc_source/container-instance-eni.md
- Add task limit per instance for M6i instance types and c5.12xlarge	
- Remove trunking unsupported instance types - c5a.8xlarge and c5ad.8xlarge
- Corrected  task limit per instance for c6gd.2xlarge	
- Minor instance type re-ordering based on EC2 documentation order
> Update supported Amazon EC2 instance types

- doc_source/wfsx-volumes.md
Update task definition JSON snippet wfsx-volumes.md
mountPoints and volumes should be on different indented lines
*Issue #196*
Modified the task definition JSON snippet with the correct syntax for the volumes and mountPoints objects for a container:
> Update snippet wfsx-volumes.md

- doc_source/ecs_cwe_events.md
Include note on "service (service-name) has reached a steady state"
> The service scheduler reports the status periodically, so you might receive this message multiple times.
(found elsewhere https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-event-messages.html#service-event-messages-list)
This is a small change. It includes a note that an ECS Service Event will be reported periodically.
> Add note for ECS Service Event reporting periodically

- doc_source/ecs-gpu.md
N / A
The correct ECS config is `ECS_ENABLE_GPU_SUPPORT`, not `ECS_ENABLED_GPU_SUPPORT`
> ecs-gpu: fix typo in env variable

- doc_source/AWS_Fargate.md
N/A
Typo in ECS Fargate log driver's configuration.
According to ECS API Documentation, the `logDriver` setting in [LogConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html)  accepts `awsfirelens` for FireLens log driver, not `firelens`.
> Fix ECS Fargate log driver name: `firelens` -> `awsfirelens`

- doc_source/specifying-sensitive-data-parameters.md
Ref: [CASE 10096430381] Chat: Job cannot connect to SSM and parameter store
IAM role to have permission "ssm:GetParameter" instead of "ssm:GetParameters"
10096430381
We tried to add permission  "ssm:GetParameters" as provided in the documentation [Specifying sensitive data using Systems Manager Parameter Store - Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html) 
But, did not work. Hence the CASE 1009643038 was created and resolved by removing "s" from "GetParameters"
> GetParameters->GetParameter

- doc_source/ecs-windows-ami-versions.md
No Issue, documentation fixes.
In the Core AMI sections, fix incorrect reference of 'Full'. Should be 'Core'
> Fix incorrect reference to 'Full' within 'Core' sections.

- doc_source/ecs-gpu.md
nvidia/cuda:11.0-base is no longer valid.  nvidia/cuda:11.0.3-base is now the correct version.  You will get an error if you try to pull this container.
> Update nvidia/cuda version to now read nvidia/cuda:11.0.3-base
