awsdocs/amazon-ecs-developer-guide

- doc_source/service-discovery.md
fix inconsistent example namespace id
> fix inconsistent example namespace id

- doc_source/retrieve-ecs-optimized_AMI.md
> More correct SSM parameter CloudFormation example

- doc_source/service-discovery.md
> this config is broken, "taskDefinition": { } should not exist

- doc_source/retrieve-ecs-optimized_AMI.md
Add AWS PowerShell example for getting Windows Amazon ECS-optimized AMI Id. This helps the AWS PowerShell users.
*Issue #, if available: N/A*
Adding the use case for AWS PowerShell. Thank you.
> Add AWS PowerShell example for getting Windows AMI

- doc_source/ecs-logs-collector.md
Updating Windows ECS log collector script info in the ECS documentation.
> Updating Windows ECS log collector script info

- doc_source/task_definition_parameters.md
fix type of  requiresCompatibilities
> fix type of requiresCompatibilities

- doc_source/common_use_cases.md
Link to AWS Open Source blog post titled "Pipelines For Container Applications Made Easy with mu"
> Add link to AWS Open Source blog post

- doc_source/ECS_GetStarted.md
*Issue #: N/A*
I fixed a minor grammar mistake.
> Fixed grammer mistake

- doc_source/ECS_Windows_getting_started.md
The CPU and Memory units in sample task definition adjusted to minimum value require to run the sample task.
> Updated Sample task definition

- doc_source/Welcome.md
> Fix spelling typo

- doc_source/task_definition_parameters.md
none
Removed a duplicate mention of the `syslog` driver.
> Removed duplicate syslog mention

- doc_source/service_limits.md
> Add details about API rate limits

- doc_source/troubleshoot-service-load-balancers.md
> Added Incorrect Load Balancer Scheme

- doc_source/fargate-capacity-providers.md
> minor typo at line 20

- doc_source/create-task-definition.md
No spacing between word and link
Added space right before the link
> Fix spacing err

- doc_source/cloudwatch_event_stream.md
Fixed typo AWS SMS queue to AWS SQS queue.
> Fix typo in cloudwatch_event_stream.md

- doc_source/task-placement-strategies.md
*Issue #, if available:* N/A
*Description of changes:* Typo fix.
> Fix typo in Task Placement Strategies guide

- doc_source/container-instance-eni.md
> Fixed typo: "in in" repetition.

- doc_source/windows_task_IAM_roles.md
*Issue # not created:*
feedback was provided  on the AWS docs page before I found this project. 
Adds a route to the metadata api (169.254.169.254) this permits a docker container to perform the following to fetch the instance ID of the container host it is running on. 
```powershell
Invoke-WebRequest http://169.254.169.254/latest/meta-data/instance-id -UseBasicParsing
```
Prior to this we also encountered the following error when using the AWS .NET SDK and some custom code, it seems it fails to access the credentials even though we have the credentials API network route established. 
```csharp
Error: Error Code: AWSSDK.Core  Type: Amazon.Runtime.AmazonServiceException  HttpStatusCode:
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() 
at …
```
> Add metadata API Net Route for Win container

- doc_source/Welcome.md
The link did not show up having an empty title.
> Fixed the link title

- doc_source/getting-started.md
AWS Copilot is an open source command line interface that makes it easy for developers to build, release, and operate production ready containerized applications on Amazon ECS and AWS Fargate.
> Add AWS Copilot to getting started guides

- doc_source/create-blue-green.md
N/A
Slight grammar modification from `an` to `a`.
> Slight grammar modification an -> a

- doc_source/getting-started-ecs-ec2.md
Cleaned up and clarified the available launch types
Just to clarify the available launch types.
> Revised launch type descriptions

- doc_source/service-discovery.md
> Caps forgetten

- doc_source/task-networking-bridge.md
> Fix typo in "Choosig" link

- doc_source/ecs-exec.md
Correcting a typo.
Just as shown in the DIFF
> Fix a typo in ecs-exec.md

- doc_source/service-discovery.md
Fixing a typo on considerations.
> Fixing a typo on Service Discovery considerations part

- doc_source/firelens-taskdef.md
Noticed that the 2nd and 3rd code blocks on this page were unusually formatted.
Updated 2nd and 3rd blocks to comport with 1st, and removed a few errant trailing tabs.
----
> harmonize json formatting

- doc_source/using_firelens.md
updated sidecar container name to match the name specified in `dependsOn`
> Update using_firelens.md: fix sidecar container name

- doc_source/launch_container_instance.md
> fixed a typo

- doc_source/asg-capacity-providers.md
The removed entry was listed 2 times in the documentation, as seen 3 items up.
> Removed double entry from list for ASG capacity providers
